### ISSUE TITLE
pip安装social_unified_creditcode的时候提示 'gbk' codec can't decode byte 0x80 in position 161: illegal multibyte sequence

### ISSUE THREAD

**Issue by Jj-Ss-Xx** [somenzz/social_unified_creditcode#1]
![image](https://user-images.githubusercontent.com/32954127/189284019-5fac1a6e-5fee-475d-9857-7a5d2aaae9fd.png)

**Comment by mpuiuo** [comment]
下载下来  在setup.py  报错的行数加个 encoding='utf-8'  进去后把json复制过去，还要在报错的方法的行数再加一个encoding='utf-8' ，然后就成功了，留了些坑给我们，但是都帮他填了

**Comment by Jj-Ss-Xx** [comment]
收到，感谢！
